[Backend](Association) Error management for required routes and tests
MTI-2023-TALA/StudAsso pull request #103
Opened 2022-05-31 10:26 UTC by TheSalfy

2022-05-31 18:49 UTC, loup-d requested changes

2022-05-31 18:49 UTC, loup-d commented on libs/backend/feature/association/src/lib/associations.controller.ts
> +      throw new BadRequestException(error?.message);
pour celle-ci peut-être plutôt mettre une `NotFoundException` (je ne connais pas son nom exact, mais ça doit être un truc du genre)

2022-06-01 08:58 UTC, TheSalfy commented on libs/backend/feature/association/src/lib/associations.controller.ts
> +      throw new BadRequestException(error?.message);
j'approuve, je le change aussi dans le user controller

2022-06-01 09:09 UTC, TheSalfy commented on libs/backend/feature/association/src/lib/associations.service.spec.ts
> +  code: PostgresError;
J'en ai besoin, car mon service vérifie que le code d'erreur c'est le PostgresERROR.UNIQUE_VIOLATION.
Du coup j'suis obligé de mock ça car sinon mon code du service marche pas

2022-06-01 09:11 UTC, TheSalfy commented on libs/backend/feature/association/src/lib/associations.controller.spec.ts
> +      expect(async () => await controller.findOneWithPresident('42')).rejects.toThrow(
okay merci! c'est corrigé :)

2022-06-01 09:16 UTC, loup-d approved these changes

2022-06-01 09:21 UTC, merged