[Backend](Users) Route to get users that contains lastname
MTI-2023-TALA/StudAsso pull request #107
Opened 2022-06-11 09:54 UTC by TheSalfy

2022-06-11 14:22 UTC, loup-d requested changes

2022-06-11 14:22 UTC, loup-d commented on libs/backend/core/repository/src/lib/user.repository.ts
> +  }
pourquoi tu ne check pas aussi le firstname ?

2022-06-11 14:22 UTC, loup-d commented on libs/backend/feature/user/src/lib/users.controller.spec.ts
> +            }),
pourquoi juste le lastname ?

2022-06-11 14:22 UTC, loup-d commented on libs/backend/feature/user/src/lib/users.service.spec.ts
> +            }),
ici aussi

2022-06-11 14:22 UTC, loup-d commented on libs/backend/feature/user/src/lib/users.service.ts
> +  }
si tu ne trouves pas l'utilisateur tu ne renvoies pas une erreur ?

2022-06-11 16:38 UTC, TheSalfy commented on libs/backend/feature/user/src/lib/users.service.ts
> +  }
Nope, la fonction renvoie la liste des users qui match
Si y'en a pas c'est une liste vide ce qui est normal

2022-06-12 11:25 UTC, loup-d commented on libs/backend/core/repository/src/lib/user.repository.ts
> +  }
ça fait bien l'un ou l'autre ou les deux ?

2022-06-12 11:29 UTC, loup-d approved these changes

2022-06-12 11:29 UTC, merged