[Shared](Docker) Docker file and docker compose for the project
MTI-2023-TALA/StudAsso pull request #126
Opened 2022-06-22 09:30 UTC by AlanasSchaeffer

2022-06-22 09:35 UTC, AloisH requested changes
Pas mal ! Mais 2-3 truc à voir

2022-06-22 09:35 UTC, AloisH commented on Dockerfile.backend
> +CMD [ "node", "dist/apps/backend/main.js" ]
On pourrait le faire en 2 stage comme pour le frontend,
dans un premier temps on le build et ensuite on lance juste le CMD mais au moins elle est clean le docker mais 
LGTM pour l'instant

2022-06-22 09:35 UTC, AloisH commented on apps/backend/Dockerfile
> +RUN npm install
fichier à supprimer

2022-06-22 09:35 UTC, AloisH commented on apps/backend/src/main.ts
> +    const document = SwaggerModule.createDocument(app, config);
petit rebase pour pas avoir ca ici ?

2022-06-22 09:35 UTC, AloisH commented on ormconfig.ts
>    password: 'password',
Ca marche encore en local apres cette modif ?

2022-06-22 09:49 UTC, AlanasSchaeffer commented on apps/backend/src/main.ts
> +    const document = SwaggerModule.createDocument(app, config);
Done

2022-06-22 09:49 UTC, AlanasSchaeffer commented on ormconfig.ts
>    password: 'password',
J'ai remis localhost, ça marche aussi bien en local que sur Docker

2022-06-22 09:49 UTC, AlanasSchaeffer commented on apps/backend/Dockerfile
> +RUN npm install
Done

2022-06-22 09:50 UTC, AlanasSchaeffer commented on Dockerfile.backend
> +CMD [ "node", "dist/apps/backend/main.js" ]
Pas bête, j'ai mis du temps sur le Docker de nouveau sur le prochain sprint je le ferais surement à ce moment là

2022-06-22 09:51 UTC, AloisH commented on ormconfig.ts
>    password: 'password',
Ok top ! Tu as bien tester en delete l'image et en la rebuild ?

2022-06-22 09:51 UTC, AloisH approved these changes
LGTM 🎉 - Check mon commentaire

2022-07-16 10:11 UTC, AlanasSchaeffer reviewed
LGTM 🎆

2022-07-16 10:15 UTC, merged