[Back](Setup) Set and organize base patterns
MTI-2023-TALA/StudAsso pull request #13
Opened 2022-03-25 10:03 UTC by loup-d

2022-03-29 16:54 UTC, AloisH requested changes

2022-03-29 16:54 UTC, AloisH commented on ormconfig.ts
> +  // migrations: [__dirname + './**/migrations/**/*{.ts,.js}'],
code mort

2022-03-29 16:54 UTC, AloisH commented on tools/migrations/1647813744740-CreateAssociationsMembersTable.ts
> +            onDelete: 'CASCADE',
c'est pas par default ?

2022-03-29 16:54 UTC, AloisH commented on tools/migrations/1647813383509-CreateAssociationsTable.ts
> +          ...dateDataColumnsWithId,
tu peux pas le mettre par default comme ca meme si on oublie de le mettre ?

2022-03-29 16:54 UTC, AloisH commented on docker-compose.yml
> +      - '3333:3333'
Faudra un jour le faire

2022-03-29 16:54 UTC, AloisH commented on apps/backend/src/main.ts
> +import {} from 'reflect-metadata';
Inutile 😡

2022-03-29 16:54 UTC, AloisH commented on apps/backend/src/associations-members/associations-members.service.ts
> +    return 'This action adds a new associationsMember';
A jeter à la .🥫

2022-03-29 18:14 UTC, TheSalfy commented on apps/backend/src/associations-members/associations-members.service.ts
> +    return 'This action adds a new associationsMember';
Il sera fait dans une PR à venir dans ce sprint normalement

2022-03-30 08:37 UTC, AloisH commented on apps/backend/src/associations-members/associations-members.service.ts
> +    return 'This action adds a new associationsMember';
il m'a dit qu'il allait le faire mtn

2022-03-30 10:51 UTC, loup-d commented on tools/migrations/1647813383509-CreateAssociationsTable.ts
> +          ...dateDataColumnsWithId,
j'ai pas trouvé comment faire c'est pour ça que j'utilise cette méthode

2022-03-30 11:00 UTC, loup-d commented on tools/migrations/1647813744740-CreateAssociationsMembersTable.ts
> +            onDelete: 'CASCADE',
j'ai rien trouvé qui indique que c'est set par défaut et dans tous les cas, comme ça, c'est explicite

2022-03-30 11:00 UTC, loup-d commented on tools/migrations/1647813383509-CreateAssociationsTable.ts
> +          ...dateDataColumnsWithId,
pas trouvé comment faire, sinon je l'aurais fait par défaut, oui

2022-03-30 11:54 UTC, AloisH approved these changes
j'approve mais j'ai fais un scan à la vite

2022-03-30 14:07 UTC, merged