[Back](Validation) validation for endpoints
MTI-2023-TALA/StudAsso pull request #14
Opened 2022-03-26 15:17 UTC by loup-d

2022-03-28 20:54 UTC, TheSalfy commented on apps/backend/src/base/ibase.service.ts
> +  remove(id: number): Promise<UpdateResult>;
Pourquoi ici on passe par un UpdateResult dans le remove ?

2022-03-28 21:10 UTC, loup-d commented on apps/backend/src/base/ibase.service.ts
> +  remove(id: number): Promise<UpdateResult>;
puisque c'est un soft delete, c'est une mise à jour de la donnée sur la colonne deleted_at donc on obtient un UpdateResult, c'est ce que renvoie nest

2022-03-28 21:19 UTC, TheSalfy commented on apps/backend/src/base/ibase.service.ts
> +  remove(id: number): Promise<UpdateResult>;
parfait! c'est carré

2022-03-29 11:58 UTC, AloisH requested changes

2022-03-29 11:58 UTC, AloisH commented on apps/backend/src/base/ibase.service.ts
> +  remove(id: number): Promise<UpdateResult>;
oui mais du coup pourquoi tu veux return un element deleted. il faut surtout dire a l'utilisateur si ca requete a bien eu lieu ou pas ?

2022-03-29 11:58 UTC, AloisH commented on apps/backend/src/associations/associations.service.spec.ts
> +import { CreateMockRepo } from '../../helpers/generic-spec/generic-service-spec';
peut-etre commence a faire des import relative ?

2022-03-29 12:58 UTC, loup-d commented on libs/shared/dtos/src/lib/base/update-base.dto.ts
> +  id: number;
oui c'est bien ce que je précise ici, j'interdis même qu'un id soit passé dans la requête

2022-03-29 12:59 UTC, loup-d commented on libs/shared/dtos/src/lib/base/update-base.dto.ts
> +  deletedAt: string;
C'est pour interdire de les ajouter/modifier à la main

2022-03-29 12:59 UTC, loup-d commented on libs/shared/dtos/src/lib/base/create-base.dto.ts
> +  deletedAt: string;
C'est pour interdire de les ajouter/modifier à la main

2022-03-29 13:01 UTC, loup-d commented on apps/backend/src/users/users.controller.ts
> +  }
hein ? pas compris.

Pourquoi ça réduit leur utilité ? Ils ne servent qu'à passer les attributs que tu veux modifier du coup c'est bon, non ?

2022-03-29 13:01 UTC, loup-d commented on apps/backend/src/associations/associations.service.spec.ts
> +import { CreateMockRepo } from '../../helpers/generic-spec/generic-service-spec';
ils sont relatifs là

2022-03-29 13:03 UTC, loup-d commented on apps/backend/src/base/ibase.service.ts
> +  remove(id: number): Promise<UpdateResult>;
si la requête a bien eu lieu, c'est passé dans le body de la réponse, c'est comme ça que fait nest par défaut, je ne sais pas si c'est un comportement à changer vraiment

2022-03-29 13:10 UTC, loup-d commented on libs/shared/dtos/src/lib/user/update-user.dto.ts
> +  email: string;
1. Les décorateurs permettent de valider la donnée qui est passée dans le dto quand on le reçoit depuis une requête utilisateur.

2. Les décorateurs viennent du package class-validator, qui est celui montré dans la doc de Nest pour la validation des Dtos.

3. Pas vraiment compris la question :/. C'est une vérification des types de données dans le code
Si on regarde `@IsString()`, c'est un appel à cette fonction par exemple:
```
export function isString(value: unknown): value is string {
  return value instanceof String || typeof value === 'string';
}
```

4. Il y en a, mais est-ce qu'on veut vraiment mettre une limite arbitraire sur la taille d'un nom, prénom ou mail ?

5. C'est déjà vérifier dans le décorateut `@IsEmail()`

2022-03-29 13:13 UTC, loup-d commented on libs/shared/dtos/src/lib/associations-member/update-associations-member.dto.ts
> +) {}
Il avait pas encore été modifié. Par défaut les Update...Dto sont des types partiels des Create...Dto car on passe au maximum tous les attributs présents dans un Create. J'ai changé ça sur ceux que j'ai modifié pour mettre des checks spécifiques en place en fonction d'update, create, etc.

2022-03-29 13:14 UTC, loup-d commented on libs/shared/dtos/src/lib/association/update-association.dto.ts
> +export class UpdateAssociationDto extends UpdateBaseDto {}
Il n'avait pas encore été fait à ce moment

2022-03-29 13:18 UTC, AloisH commented on apps/backend/src/base/ibase.service.ts
> +  remove(id: number): Promise<UpdateResult>;
donc c'est normal que nest te renvoie un item que tu as choisis de return ? J'ai pas compris...
C'est bien toi qui choisit ce que tu return ?

2022-03-29 13:19 UTC, AloisH commented on libs/shared/dtos/src/lib/base/update-base.dto.ts
> +  id: number;
alors comment tu update un objet sans son id ?

2022-03-29 13:21 UTC, AloisH commented on libs/shared/dtos/src/lib/base/update-base.dto.ts
> +  deletedAt: string;
mais dans une requetes de base c'est pas interdit de mettre des elements qui ne sont pas dans les dto ?

2022-03-29 13:23 UTC, AloisH commented on apps/backend/src/users/users.controller.ts
> +  }
le but d'un dto c'est d'exposer le contrat que tu veux donner à tes clients pour qu'ils puissent appeler facilement ton API, la tu lui dit que pour un update il ne doit pas lui passer de id et que du coup il doit le savoir apres ca me va mais du coup si ca reduit.
Impossible avec un dto de savoir si il doit y avoir des params dans la requetes ou non

2022-03-29 13:24 UTC, AloisH commented on apps/backend/src/associations/associations.service.spec.ts
> +import { CreateMockRepo } from '../../helpers/generic-spec/generic-service-spec';
non-relatif*

2022-03-29 13:26 UTC, loup-d commented on libs/shared/dtos/src/lib/base/update-base.dto.ts
> +  deletedAt: string;
non

2022-03-29 13:28 UTC, loup-d commented on apps/backend/src/users/users.controller.ts
> +  }
ah oui je vois ok, je peux modifier ça, mais je ne mettrais pas les params dans le même Dto que le body, sinon nest ne comprendra pas que c'est un paramètre

2022-03-29 13:29 UTC, AloisH commented on apps/backend/src/base/ibase.service.ts
> +  remove(id: number): Promise<UpdateResult>;
ok c'est bon ca me va je pensais que ca return l'objet modifier (aka tous ces champs avec les delete_at le name l'id ect

2022-03-29 13:30 UTC, loup-d commented on apps/backend/src/associations/associations.service.spec.ts
> +import { CreateMockRepo } from '../../helpers/generic-spec/generic-service-spec';
ah ok, du coup avec des paths en @qqch ?

2022-03-29 15:01 UTC, AloisH approved these changes

2022-03-29 15:18 UTC, merged