[Backend](Pagination) Add pagination to findAlls
MTI-2023-TALA/StudAsso pull request #207
Opened 2022-10-16 18:20 UTC by TheSalfy

* removed some useless testing (which will be removed anyway on another PR)
* removed few check on deletedAt in queries (never used, because no soft delete yet and will be checked in middleware)

2022-10-16 18:25 UTC, AloisH requested changes

2022-10-16 18:25 UTC, AloisH commented on libs/backend/core/repository/src/lib/association-offer-application.repository.ts
> +    const limit = queryPaginationModel.limit ? queryPaginationModel.limit : PAGINATION_BASE_LIMIT;
possible de soit faire une fonction pour pour mettre la bonne valeur dedans ?

2022-10-16 18:25 UTC, AloisH commented on libs/backend/core/model/src/lib/query.model.ts
> +}
par tout hasard tu peux pas faire ca pour simplifier le code ? 
```suggestion
export class QueryPaginationModel {
  offset?: number = PAGINATION_BASE_OFFSET;
  limit?: number = PAGINATION_BASE_LIMIT;
}
```

2022-10-16 18:25 UTC, AloisH commented on libs/backend/core/model/src/lib/query.model.ts
> +}
A tester

2022-10-17 10:50 UTC, AloisH approved these changes
LGTM 🎉

2022-10-17 11:27 UTC, loup-d approved these changes
LGTM 🎉

2022-10-17 11:32 UTC, merged